// ==============================================
// ENUMS - TypeScript interfaces for Prisma enums
// ==============================================

export enum UserRole {
  PLATFORM_ADMIN = 'PLATFORM_ADMIN',
  CLIENT = 'CLIENT',
  CLIENT_MEMBER = 'CLIENT_MEMBER',
  AGENCY_MEMBER = 'AGENCY_MEMBER',
}

export enum AgencyMemberFunction {
  DESIGNER = 'DESIGNER',
  DEVELOPER = 'DEVELOPER',
  SALES = 'SALES',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  ACCOUNT_MANAGER = 'ACCOUNT_MANAGER',
  CREATIVE_DIRECTOR = 'CREATIVE_DIRECTOR',
  TECHNICAL_LEAD = 'TECHNICAL_LEAD',
}

// ProjectStatus removed - using ContractStatus instead

export enum ContractStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  TERMINATED = 'TERMINATED',
  EXPIRED = 'EXPIRED',
}

export enum ProposalStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum RoomType {
  GENERAL = 'GENERAL',
  CONTRACT_SPECIFIC = 'CONTRACT_SPECIFIC',
  CLIENT_SPECIFIC = 'CLIENT_SPECIFIC',
  AGENCY_INTERNAL = 'AGENCY_INTERNAL',
}

export enum ActivityVerb {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  ASSIGNED = 'ASSIGNED',
  UNASSIGNED = 'UNASSIGNED',
  MESSAGE_SENT = 'MESSAGE_SENT',
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DOWNLOADED = 'FILE_DOWNLOADED',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  PROPOSAL_ACCEPTED = 'PROPOSAL_ACCEPTED',
  PROPOSAL_DECLINED = 'PROPOSAL_DECLINED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UNASSIGNED = 'TASK_UNASSIGNED',
}

export enum PermissionType {
  READ = 'READ',
  WRITE = 'WRITE',
  ADMIN = 'ADMIN',
  NONE = 'NONE',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_REVIEW = 'IN_REVIEW',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD',
}
